# Generated by Django 4.2.3 on 2023-07-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
